### PR TITLE
Improve navigator.

### PR DESCRIPTION
**Pull request by argelius**
@philolo1 I simplified the Navigator component to only use a state variable called `routes` and removed the `pages` variable so now it will re-render its children when the Navigator is rendered. There are some people having issues with this.

I also simplified how it communicates with the core navigator. Now it will just send a function that updates the state and resolves when the DOM has been updated.

I'm not really sure about the events parameters that we added recently.

### CODE REVIEW

**Comment by philolo1** [comment]
@argelius As far as I can see you are rerendering everything on render right and also when you push? Its strange if you call pushPage to rerender all the pages.

**Comment by argelius** [comment]
@philolo1 Actually only the top two pages are rendered since I use `slice` in the render function.

**Comment by philolo1** [comment]
@argelius ok, so you are only rendering the last two pages in the render function? It seems a little bit strange to me, so what happens to the 1st page, if you have 3 pages, and does resetPageStack work?

**Comment by argelius** [comment]
Closing this since it was solved in another way.

**Pull request closed without merging**
